ALTER TABLE usuarios ALTER COLUMN nombre DROP NOT NULL;
ALTER TABLE usuarios ALTER COLUMN apellidos DROP NOT NULL;
ALTER TABLE usuarios ALTER COLUMN documento_identidad DROP NOT NULL;
ALTER TABLE usuarios ALTER COLUMN fecha_nacimiento DROP NOT NULL;
ALTER TABLE usuarios ALTER COLUMN direccion DROP NOT NULL;
ALTER TABLE usuarios ALTER COLUMN telefono DROP NOT NULL;
ALTER TABLE usuarios ALTER COLUMN salario_base DROP NOT NULL;